[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "telegraf"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://host.docker.internal:8086"]
  database = "k6"
  skip_database_creation = true

[[inputs.rabbitmq]]
  url = "http://rabbitmq:15672"
  username = "guest"
  password = "guest"
