import { Router } from 'express';
import axios from 'axios';

const router = Router();

router.post('/summarize', async (req, res) => {
    const { text } = req.body;
    if (!text) {
        return res.status(400).json({ message: 'Text is required' });
    }

    try {
        console.log("simulating external LLM call...");
        await axios.get('https://httpbin.org/delay/2'); // Simulate network call

        // Mock summary logic (simple truncation)
        const summary = text.length > 100 ? text.substring(0, 100) + '...' : text;

        res.json({
            originalLength: text.length,
            summary,
            note: "Generated by LLM Service (Simulated)"
        });
    } catch (error) {
        console.error("LLM Service Error:", error);
        res.status(500).json({ message: "Failed to generate summary" });
    }
});

export default router;
