import express from 'express';
import dotenv from 'dotenv';
import axios from 'axios';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3005;

app.use(express.json());

app.get('/health', (req, res) => {
    res.json({ status: 'LLM Service is running' });
});

app.post('/summarize', async (req, res) => {
    const { text } = req.body;
    if (!text) {
        return res.status(400).json({ message: 'Text is required' });
    }

    try {
        // Network Connected Challenge:
        // We make a real HTTP request to an external API. 
        // Since we don't have a paid LLM key, we will simulate the "network delay" and "processing" 
        // by calling a public API (Text Processing API if available, or just a dummy fetch).
        // Let's use https://httpbin.org/delay/2 to simulate network latency of 2 seconds.

        console.log("simulating external LLM call...");
        await axios.get('https://httpbin.org/delay/2'); // Simulate network call

        // Mock summary logic (simple truncation)
        const summary = text.length > 100 ? text.substring(0, 100) + '...' : text;

        res.json({
            originalLength: text.length,
            summary,
            note: "Generated by LLM Service (Simulated)"
        });
    } catch (error) {
        console.error("LLM Service Error:", error);
        res.status(500).json({ message: "Failed to generate summary" });
    }
});

app.listen(PORT, () => {
    console.log(`LLM Service running on port ${PORT}`);
});
