version: '3.8'
services:
  monolith-backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    environment:
      - MONGO_URI=mongodb+srv://nedim:8011@fyp.aubab4u.mongodb.net/?appName=FYP

  monolith-client:
    build: ./client
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./client:/app
      - /app/node_modules
