version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/dashboards/k6.json:/var/lib/grafana/dashboards/k6.json:ro
      - ./grafana/dashboards/architectural_contrast.json:/var/lib/grafana/dashboards/architectural_contrast.json:ro

  k6:
    image: grafana/k6:latest
    profiles:
      - testing
    volumes:
      - ./loadtest.js:/scripts/loadtest.js:ro
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      # Default target, can be overridden by user when executing the profile
      - TARGET_URL=${TARGET_URL:-http://host.docker.internal:8080}
    command: run /scripts/loadtest.js
