services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file: ./api-gateway/.env
    environment:
      - SERVICE_NAME=api-gateway
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:3004
      - LLM_SERVICE_URL=http://llm-service:3005
      - CONTENT_CREATOR_URL=http://content-creator:3008
    depends_on:
      - auth-service
      - product-service
      - order-service
    restart: on-failure


  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    env_file: ./services/auth-service/.env
    environment:
      - DATABASE_URL=postgresql://postgres.omzkmugaxusblmunctwp:8011nedimK216@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?schema=public

  product-service:
    build: ./services/product-service
    ports:
      - "3002:3002"
    env_file: ./services/product-service/.env
    environment:
      - SERVICE_NAME=product-service
      - REDIS_URL=rediss://default:gQAAAAAAAUofAAIgcDI4NTNjZTQ0MGUwMWU0OWQ1OWI0MjMzZDYwYTBjNDRiOQ@set-monster-84511.upstash.io:6379
      - MONGO_URI=mongodb+srv://nedim:8011@fyp.aubab4u.mongodb.net/?appName=FYP
      - RABBITMQ_URL=amqps://bdqiubqw:hXeeSv2jUFVIxRXvxYsUFSvBzJ4hx6Xr@seahorse.lmq.cloudamqp.com/bdqiubqw
    restart: on-failure

  order-service:
    build: ./services/order-service
    ports:
      - "3003:3003"
    env_file: ./services/order-service/.env
    environment:
      - SERVICE_NAME=order-service
      - MONGO_URI=mongodb+srv://nedim:8011@fyp.aubab4u.mongodb.net/?appName=FYP
      - RABBITMQ_URL=amqps://bdqiubqw:hXeeSv2jUFVIxRXvxYsUFSvBzJ4hx6Xr@seahorse.lmq.cloudamqp.com/bdqiubqw
    restart: on-failure

  recommendation-service:
    build: ./services/recommendation-service
    ports:
      - "3004:3004"
    env_file: ./services/recommendation-service/.env
    environment:
      - DATABASE_URL=postgresql://postgres.omzkmugaxusblmunctwp:8011nedimK216@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?schema=public

  traffic-service:
    build: ./services/traffic-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
    depends_on:
      - api-gateway

  llm-service:
    build: ./services/llm-service
    ports:
      - "3005:3005"
    env_file: ./services/llm-service/.env
    environment:
      - PORT=3005

  content-creator:
    build: ./services/content-creator
    ports:
      - "3008:3008"
    environment:
      - PORT=3008

  client:
    build: ./client
    ports:
      - "5178:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./client:/app
      - /app/node_modules

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pumba:
    image: gaiaadm/pumba:latest
    profiles: ["chaos"]
    command: netem --duration 5m delay --time 5000 re2:.*llm-service.*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Web UI
      - "4318:4318" # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true

